/**
 * Roommate Finder System - R. C. Patel Institute of Technology, Shirpur Edition
 * Tailored exclusively for students of R. C. Patel Institute of Technology, Shirpur
 * Strict Gender-Separated Accommodations: Separate Boys Rooms and Girls Rooms
 * Key student residential areas: Near College, Kazi Nagar, Sandipani Colony, Sandipani Colony 2, Nimzari Naka, Karvand Road
 */

const DEFAULT_PROFILES = [
  {
    id: "rcp-101",
    name: "Pranav Borse",
    age: 21,
    gender: "Male",
    seekingGender: "Male",
    avatar: "👨‍💻",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Nimzari Naka, Shirpur",
    monthlyBudget: 3200,
    foodPreference: "Vegetarian",
    sleepSchedule: "Night Owl",
    studyPreference: "Group Study",
    lifestyle: "Social",
    habits: ["Coding", "Tech Geek", "Non-Smoker", "Night Coder"],
    phone: "+91 94030 55112",
    email: "pranav.borse@rcpit.ac.in",
    about: "Final year Computer Engineering student at R. C. Patel Institute of Technology. Seeking a male roommate for boys 2BHK flat near Nimzari Naka. I love coding hackathons, late-night tea breaks, and sharing rent.",
    moveInDate: "Immediate",
    roomType: "Boys Shared Flat (Male Only)"
  },
  {
    id: "rcp-102",
    name: "Sneha Patil",
    age: 19,
    gender: "Female",
    seekingGender: "Female",
    avatar: "👩‍🎓",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Near College, Shirpur",
    monthlyBudget: 2800,
    foodPreference: "Vegetarian",
    sleepSchedule: "Early Sleeper",
    studyPreference: "Quiet",
    lifestyle: "Quiet",
    habits: ["Early Bird", "Non-Smoker", "Studious", "Chai Lover"],
    phone: "+91 97645 88120",
    email: "sneha.patil@rcpit.ac.in",
    about: "Second-year IT student at R. C. Patel Institute of Technology. Seeking a female roommate for a quiet girls room located Near College within 2 minutes walk to RCPIT campus gate.",
    moveInDate: "Immediate",
    roomType: "Girls Sharing Room (Female Only)"
  },
  {
    id: "rcp-103",
    name: "Rohan Deshmukh",
    age: 20,
    gender: "Male",
    seekingGender: "Male",
    avatar: "🧑‍💻",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Nimzari Naka, Shirpur",
    monthlyBudget: 3500,
    foodPreference: "Both",
    sleepSchedule: "Night Owl",
    studyPreference: "Group Study",
    lifestyle: "Social",
    habits: ["Gamer", "Gym Freak", "Socializer", "Non-Smoker"],
    phone: "+91 91580 33412",
    email: "rohan.deshmukh@rcpit.ac.in",
    about: "Third-year AI & Data Science student at R. C. Patel Institute of Technology living near Nimzari Naka. Looking for male roommates for a boys 3BHK flat. Evening gym enthusiast, friendly and cooperative.",
    moveInDate: "Immediate",
    roomType: "Boys Furnished Flat (Male Only)"
  },
  {
    id: "rcp-104",
    name: "Pooja Chaudhari",
    age: 20,
    gender: "Female",
    seekingGender: "Female",
    avatar: "👩‍🔬",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Kazi Nagar, Shirpur",
    monthlyBudget: 3000,
    foodPreference: "Vegetarian",
    sleepSchedule: "Flexible",
    studyPreference: "Quiet",
    lifestyle: "Moderate",
    habits: ["Non-Smoker", "Music lover", "Bookworm"],
    phone: "+91 99200 67123",
    email: "pooja.c@rcpit.ac.in",
    about: "Computer Engineering student at R. C. Patel Institute of Technology living in Kazi Nagar. Looking for a girl roommate for girls 1BHK. Clean, tidy, and peaceful study atmosphere during exams.",
    moveInDate: "Next Month",
    roomType: "Girls Shared Flat (Female Only)"
  },
  {
    id: "rcp-105",
    name: "Karan Shinde",
    age: 21,
    gender: "Male",
    seekingGender: "Male",
    avatar: "👨‍🔧",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Kazi Nagar, Shirpur",
    monthlyBudget: 2500,
    foodPreference: "Vegetarian",
    sleepSchedule: "Early Sleeper",
    studyPreference: "Quiet",
    lifestyle: "Quiet",
    habits: ["Early Bird", "Non-Smoker", "Simple Living"],
    phone: "+91 94222 19876",
    email: "karan.shinde@rcpit.ac.in",
    about: "Mechanical Engineering student at R. C. Patel Institute of Technology. Looking for a budget-friendly boys shared room in Kazi Nagar. Simple, peaceful lifestyle, focused on campus placements.",
    moveInDate: "Immediate",
    roomType: "Boys Room Sharing (Male Only)"
  },
  {
    id: "rcp-106",
    name: "Tanvi Kulkarni",
    age: 19,
    gender: "Female",
    seekingGender: "Female",
    avatar: "👩‍💻",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Sandipani Colony, Shirpur",
    monthlyBudget: 3400,
    foodPreference: "Vegetarian",
    sleepSchedule: "Night Owl",
    studyPreference: "Flexible",
    lifestyle: "Moderate",
    habits: ["Clean Freak", "Coding", "Chai Lover", "Non-Smoker"],
    phone: "+91 93701 44890",
    email: "tanvi.k@rcpit.ac.in",
    about: "First-year Computer Engineering girl student at R. C. Patel Institute of Technology. Searching for a female roommate for a girls flat in Sandipani Colony. Safe neighborhood, cooperative and clean.",
    moveInDate: "Within 10 days",
    roomType: "Girls Shared Flat (Female Only)"
  },
  {
    id: "rcp-107",
    name: "Yash More",
    age: 22,
    gender: "Male",
    seekingGender: "Male",
    avatar: "👨‍💼",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Sandipani Colony, Shirpur",
    monthlyBudget: 2700,
    foodPreference: "Both",
    sleepSchedule: "Flexible",
    studyPreference: "Group Study",
    lifestyle: "Moderate",
    habits: ["Cricket Lover", "Tea Addict", "Helpful", "Non-Smoker"],
    phone: "+91 98901 77234",
    email: "yash.more@rcpit.ac.in",
    about: "Civil Engineering final-year at R. C. Patel Institute of Technology. Looking for male roommates in Sandipani Colony to share flat expenses. Peaceful atmosphere, happy to share grocery runs.",
    moveInDate: "Immediate",
    roomType: "Boys Double Sharing (Male Only)"
  },
  {
    id: "rcp-108",
    name: "Tejas Chaudhari",
    age: 20,
    gender: "Male",
    seekingGender: "Male",
    avatar: "👨‍🎓",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Nimzari Naka, Shirpur",
    monthlyBudget: 3600,
    foodPreference: "Vegetarian",
    sleepSchedule: "Early Sleeper",
    studyPreference: "Quiet",
    lifestyle: "Quiet",
    habits: ["Non-Smoker", "Studious", "Chai Lover"],
    phone: "+91 94239 88114",
    email: "tejas.c@rcpit.ac.in",
    about: "E&TC student at R. C. Patel Institute of Technology living right at Nimzari Naka. 2-minute walk to market. Seeking a neat male flatmate to share rent and electricity bills in boys flat.",
    moveInDate: "Immediate",
    roomType: "Boys 2BHK Flat (Male Only)"
  },
  {
    id: "rcp-109",
    name: "Ananya Rajput",
    age: 20,
    gender: "Female",
    seekingGender: "Female",
    avatar: "👩‍🎨",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Sandipani Colony 2, Shirpur",
    monthlyBudget: 3200,
    foodPreference: "Both",
    sleepSchedule: "Flexible",
    studyPreference: "Quiet",
    lifestyle: "Moderate",
    habits: ["Non-Smoker", "Neat & Tidy", "Friendly"],
    phone: "+91 98811 00234",
    email: "ananya.r@rcpit.ac.in",
    about: "Information Technology student at R. C. Patel Institute of Technology living in Sandipani Colony 2. Looking for a respectful girl roommate in a modern girls flat with reliable water & electricity.",
    moveInDate: "Next Month",
    roomType: "Girls Shared 2BHK (Female Only)"
  },
  {
    id: "rcp-110",
    name: "Siddharth Ahire",
    age: 21,
    gender: "Male",
    seekingGender: "Male",
    avatar: "🧑‍💻",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Near College, Shirpur",
    monthlyBudget: 4000,
    foodPreference: "Vegetarian",
    sleepSchedule: "Night Owl",
    studyPreference: "Quiet",
    lifestyle: "Quiet",
    habits: ["Non-Smoker", "Introvert", "Neat & Organized"],
    phone: "+91 98205 91823",
    email: "sid.ahire@rcpit.ac.in",
    about: "Third-year Computer student at R. C. Patel Institute of Technology. Looking for a male flatmate for quiet twin-sharing room right Near College campus gate. Very peaceful and dedicated to projects.",
    moveInDate: "Immediate",
    roomType: "Boys Twin Sharing (Male Only)"
  },
  {
    id: "rcp-111",
    name: "Neha Badgujar",
    age: 21,
    gender: "Female",
    seekingGender: "Female",
    avatar: "👩‍🎓",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Sandipani Colony 2, Shirpur",
    monthlyBudget: 2900,
    foodPreference: "Vegetarian",
    sleepSchedule: "Early Sleeper",
    studyPreference: "Quiet",
    lifestyle: "Quiet",
    habits: ["Studious", "Non-Smoker", "Calm Nature"],
    phone: "+91 97633 44001",
    email: "neha.b@rcpit.ac.in",
    about: "Electrical Engineering student at R. C. Patel Institute of Technology. Peaceful girls room sharing in Sandipani Colony 2. Safe residential area with peaceful study vibes.",
    moveInDate: "Immediate",
    roomType: "Girls Twin Sharing (Female Only)"
  },
  {
    id: "rcp-112",
    name: "Harshal Sonawane",
    age: 20,
    gender: "Male",
    seekingGender: "Male",
    avatar: "👨‍🏫",
    college: "R. C. Patel Institute of Technology, Shirpur",
    location: "Kazi Nagar, Shirpur",
    monthlyBudget: 2600,
    foodPreference: "Both",
    sleepSchedule: "Flexible",
    studyPreference: "Group Study",
    lifestyle: "Moderate",
    habits: ["Friendly", "Non-Smoker", "Sports Enthusiast"],
    phone: "+91 91566 22890",
    email: "harshal.s@rcpit.ac.in",
    about: "Data Science student at R. C. Patel Institute of Technology. Looking for male flatmates in Kazi Nagar boys flat. Cooperative, down-to-earth, and always ready to split household chores.",
    moveInDate: "Immediate",
    roomType: "Boys Flat Sharing (Male Only)"
  }
];

// Available avatar options for new profile creation
const AVATAR_OPTIONS = [
  "👨‍🎓", "👩‍🎓", "🧑‍💻", "👩‍💻", "👨‍🔬", "👩‍🔬", 
  "👨‍🎨", "👩‍🎨", "👨‍💼", "👩‍💼", "🧑‍🎤", "👩‍⚕️"
];

// Supported Shirpur student residential localities
const LOCATIONS = [
  "All Shirpur Localities",
  "Near College",
  "Kazi Nagar",
  "Sandipani Colony",
  "Sandipani Colony 2",
  "Nimzari Naka",
  "Karvand Road"
];
