services:
  - type: web
    name: roommate-finder-rcpit
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
